worker_processes auto; # Uses all available CPU cores for maximum concurrency

events {
    worker_connections 8192; # Increased further for huge burst traffic
    multi_accept on; # Accept as many connections as possible, after getting a notification about a new connection
}

http {
    # Define upstream groups for load balancing
    upstream order_service {
        server order-service:14000;
    }

    upstream user_service {
        server user-service:14001;
    }

    upstream product_service {
        server product-service:15000;
    }

    server {
        listen 4001; # Our unified entry point

        # Route Order Service requests
        location /order {
            proxy_pass http://order_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route User Service requests
        location /user {
            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route Product Service requests
        location /product {
            proxy_pass http://product_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}